version: "3.8"

services:
  mysql:
    image: mysql:8.0.40
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    command: [
      "--innodb-buffer-pool-size=64M",
      "--innodb-log-file-size=32M",
      "--innodb-log-buffer-size=8M",
      "--max-connections=50",
      "--performance-schema=OFF",
      "--table-definition-cache=400",
      "--table-open-cache=64"
    ]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 768M

  redis:
    image: redis:7.0
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--maxmemory", "128mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    deploy:
      resources:
        limits:
          memory: 200M

  app:
    depends_on:
      - mysql
      - redis
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 300M
